import { render, screen } from "@testing-library/react";
import { StatusBadge } from "./status-badge";
import { describe, it, expect } from "vitest";

describe("StatusBadge", () => {
    it("renders correct label", () => {
        render(<StatusBadge status="Running" />);
        expect(screen.getByText("Running")).toBeDefined();
    });

    it("applies variant based on status", () => {
        const { container } = render(<StatusBadge status="Failed" />);
        // Since we can't easily check class names generated by cva without complex setup, 
        // we verify the element exists and contains the text.
        // Ideally we would check for 'bg-destructive' class or similar.
        expect(screen.getByText("Failed")).toBeDefined();
        // Verify it renders a Badge (div)
        expect(container.querySelector("div")).toBeDefined();
    });

    it("handles unknown status gracefully", () => {
        render(<StatusBadge status="UnknownStatus" />);
        expect(screen.getByText("UnknownStatus")).toBeDefined();
    });
});
