import { SSPControlSection, CapabilityCompliance } from '@golden/schema-registry';

interface StalenessResult {
    stale: boolean;
    reason?: string;
}

interface CapabilityRegistry {
    get(id: string): { security?: { compliance?: CapabilityCompliance } } | undefined;
}

/**
 * Check if an SSP section is stale due to capability changes.
 */
export function checkStaleness(
    section: SSPControlSection,
    capabilityRegistry: CapabilityRegistry
): StalenessResult {
    for (const [capId, recordedVersion] of Object.entries(section.source.autoGenerated.mappingVersions)) {
        const capability = capabilityRegistry.get(capId);
        if (!capability) {
            return { stale: true, reason: `Capability ${capId} no longer exists` };
        }

        // Check if security.compliance exists
        if (!capability.security?.compliance) {
            // If it previously had compliance (implied by it being in the mapping), but now doesn't, it's stale/broken
            return { stale: true, reason: `Capability ${capId} no longer has compliance metadata` };
        }

        const currentVersion = capability.security.compliance.mappingVersion;
        if (currentVersion > recordedVersion) {
            return {
                stale: true,
                reason: `Capability ${capId} control mappings updated (${recordedVersion} -> ${currentVersion})`
            };
        }
    }

    return { stale: false };
}
