#!/bin/bash
#
# summarize-repo.sh — Fetch and summarize key information from a GitHub repository
#
# Usage: ./summarize-repo.sh <github-repo-url>
# Example: ./summarize-repo.sh https://github.com/oscal-compass/compliance-trestle
#
# Output: Markdown summary of the repository including:
#   - Project description
#   - Key commands/operations
#   - Data formats
#   - Docker images (if any)
#   - Installation instructions
#

set -e

REPO_URL="${1:-}"

if [ -z "$REPO_URL" ]; then
  echo "Usage: $0 <github-repo-url>"
  echo "Example: $0 https://github.com/oscal-compass/compliance-trestle"
  exit 1
fi

# Extract owner/repo from URL
REPO_PATH=$(echo "$REPO_URL" | sed -E 's|https?://github\.com/||' | sed 's|/$||')
OWNER=$(echo "$REPO_PATH" | cut -d'/' -f1)
REPO=$(echo "$REPO_PATH" | cut -d'/' -f2)

echo "# Repository Summary: $OWNER/$REPO"
echo ""
echo "**Source:** $REPO_URL"
echo "**Generated:** $(date -Iseconds)"
echo ""

# Fetch repo metadata from GitHub API
echo "## Basic Info"
echo ""

REPO_DATA=$(curl -s "https://api.github.com/repos/$OWNER/$REPO")

DESCRIPTION=$(echo "$REPO_DATA" | jq -r '.description // "No description"')
LANGUAGE=$(echo "$REPO_DATA" | jq -r '.language // "Unknown"')
STARS=$(echo "$REPO_DATA" | jq -r '.stargazers_count // 0')
TOPICS=$(echo "$REPO_DATA" | jq -r '.topics // [] | join(", ")')

echo "- **Description:** $DESCRIPTION"
echo "- **Primary Language:** $LANGUAGE"
echo "- **Stars:** $STARS"
echo "- **Topics:** $TOPICS"
echo ""

# Fetch README
echo "## README Summary"
echo ""

README_DATA=$(curl -s "https://api.github.com/repos/$OWNER/$REPO/readme")
README_CONTENT=$(echo "$README_DATA" | jq -r '.content // ""' | base64 -d 2>/dev/null || echo "")

if [ -n "$README_CONTENT" ]; then
  # Extract first section (description)
  echo "### Description"
  echo "$README_CONTENT" | head -50
  echo ""
  echo "---"
  echo "_Showing first 50 lines of README. See full content at $REPO_URL_"
else
  echo "_README not available via API_"
fi
echo ""

# Check for Docker images
echo "## Docker Images"
echo ""

# Check GitHub Container Registry
GHCR_IMAGE="ghcr.io/$OWNER/$REPO"
echo "- **GitHub Container Registry:** \`$GHCR_IMAGE\` (check availability)"

# Check Docker Hub
DOCKERHUB_IMAGE="$OWNER/$REPO"
echo "- **Docker Hub:** \`$DOCKERHUB_IMAGE\` (check availability)"
echo ""

# Check for common config files
echo "## Detected Configuration"
echo ""

CONTENTS=$(curl -s "https://api.github.com/repos/$OWNER/$REPO/contents")

detect_file() {
  local filename="$1"
  local description="$2"
  if echo "$CONTENTS" | jq -e ".[] | select(.name == \"$filename\")" > /dev/null 2>&1; then
    echo "- ✓ **$description** found: \`$filename\`"
  fi
}

detect_file "pyproject.toml" "Python project"
detect_file "setup.py" "Python setup"
detect_file "go.mod" "Go module"
detect_file "Cargo.toml" "Rust project"
detect_file "package.json" "Node.js project"
detect_file "Dockerfile" "Dockerfile"
detect_file "docker-compose.yml" "Docker Compose"
detect_file "openapi.yaml" "OpenAPI Spec"
detect_file "openapi.json" "OpenAPI Spec"
detect_file ".github" "GitHub Actions"

echo ""

# Suggest Harmony integration approach
echo "## Suggested Integration Approach"
echo ""

case "$LANGUAGE" in
  Python)
    echo "- **Pattern:** COMMANDER (CLI wrapper)"
    echo "- **Container:** Wrap Python CLI in Dagger container"
    echo "- **Reference:** \`.cursor/skills/external-cli-wrapper/SKILL.md\`"
    ;;
  Go)
    echo "- **Pattern:** COMMANDER (CLI wrapper)"
    echo "- **Container:** Use official Docker image or build from source"
    echo "- **Reference:** See \`trivy-scanner.capability.ts\` for Go CLI pattern"
    ;;
  TypeScript|JavaScript)
    echo "- **Pattern:** CONNECTOR or native import"
    echo "- **Approach:** Direct npm dependency or API wrapper"
    ;;
  *)
    echo "- **Pattern:** Determine based on available APIs/CLIs"
    echo "- **Research:** Check for REST API, GraphQL, or CLI tools"
    ;;
esac

echo ""
echo "---"
echo ""
echo "_Generated by summarize-repo.sh from external-cli-wrapper skill_"
