/**
 * packages/blueprints/src/registry.ts
 * In-process registry for WCS blueprints by ID (deterministic discovery).
 *
 * Generated by @golden/path:sync (deterministic).
 */
import { releasePipelineBlueprintDescriptor } from './descriptors/release-pipeline.descriptor.js';
import { blueGreenDeployBlueprintDescriptor } from './descriptors/blue-green-deploy.descriptor.js';
import { progressiveRolloutBlueprintDescriptor } from './descriptors/progressive-rollout.descriptor.js';
import { echoBlueprintDescriptor } from './descriptors/echo.descriptor.js';
import { mathPipelineBlueprintDescriptor } from './descriptors/math-pipeline.descriptor.js';
import type { BlueprintDescriptor } from './descriptors/types.js';

export interface BlueprintRegistryEntry {
  blueprintId: string;
  workflowType: string;
  descriptor: BlueprintDescriptor;
}

export type BlueprintRegistry = Map<string, BlueprintRegistryEntry>;

export function createBlueprintRegistry(): BlueprintRegistry {
  // Deterministic ordering: sorted by blueprintId.
  return new Map<string, BlueprintRegistryEntry>([
    ['blueprints.ci.release-pipeline', { blueprintId: 'blueprints.ci.release-pipeline', workflowType: 'releasePipelineWorkflow', descriptor: releasePipelineBlueprintDescriptor }],
    ['blueprints.deploy.blue-green', { blueprintId: 'blueprints.deploy.blue-green', workflowType: 'blueGreenDeployWorkflow', descriptor: blueGreenDeployBlueprintDescriptor }],
    ['blueprints.traffic.progressive-rollout', { blueprintId: 'blueprints.traffic.progressive-rollout', workflowType: 'progressiveRolloutWorkflow', descriptor: progressiveRolloutBlueprintDescriptor }],
    ['workflows.echo', { blueprintId: 'workflows.echo', workflowType: 'echoWorkflow', descriptor: echoBlueprintDescriptor }],
    ['workflows.math_pipeline', { blueprintId: 'workflows.math_pipeline', workflowType: 'mathPipelineWorkflow', descriptor: mathPipelineBlueprintDescriptor }],
  ]);
}

export function getBlueprint(registry: BlueprintRegistry, blueprintId: string): BlueprintRegistryEntry {
  const bp = registry.get(blueprintId);
  if (!bp) throw new Error(`Blueprint not found: ${blueprintId}`);
  return bp;
}
