import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { SSPControlSection } from '@golden/schema-registry';

// Mock Data
const mockSSP: SSPControlSection[] = [
    {
        controlId: 'AC-2',
        stale: true,
        source: {
            autoGenerated: {
                narrative: 'Satisfied by Capability A. Ref: impl/auth.',
                generatedAt: new Date().toISOString(),
                sourceCapabilities: ['cap-auth'],
                mappingVersions: { 'cap-auth': 2 }
            },
            humanOverride: {
                narrative: 'Satisfied by Capability A with extra manual checks.',
                editedBy: 'user@example.com',
                editedAt: new Date(Date.now() - 86400000).toISOString()
            }
        },
        evidenceLinks: ['link/to/evidence'],
        responsibleRoles: ['IT Admin']
    }
];

export default function SSPEditor() {
    const [sections, setSections] = useState<SSPControlSection[]>(mockSSP);
    const [editingId, setEditingId] = useState<string | null>(null);
    const [editValue, setEditValue] = useState('');

    const handleEdit = (section: SSPControlSection) => {
        setEditingId(section.controlId);
        setEditValue(section.source.humanOverride?.narrative || section.source.autoGenerated.narrative);
    };

    const handleSave = (id: string) => {
        setSections(prev => prev.map(s => {
            if (s.controlId === id) {
                return {
                    ...s,
                    source: {
                        ...s.source,
                        humanOverride: {
                            narrative: editValue,
                            editedBy: 'current-user', // Mock
                            editedAt: new Date().toISOString()
                        }
                    },
                    stale: false // resolve staleness on edit
                };
            }
            return s;
        }));
        setEditingId(null);
    };

    return (
        <div className="container mx-auto p-6 space-y-6">
            <h1 className="text-3xl font-bold">SSP Editor</h1>

            <div className="space-y-4">
                {sections.map(section => (
                    <Card key={section.controlId} className={section.stale ? 'border-orange-300' : ''}>
                        <CardHeader>
                            <div className="flex items-center justify-between">
                                <CardTitle className="font-mono">{section.controlId}</CardTitle>
                                {section.stale && <Badge variant="secondary" className="text-orange-600">Stale / Conflict</Badge>}
                            </div>
                            <CardDescription>
                                Sources: {section.source.autoGenerated.sourceCapabilities.join(', ')}
                            </CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            {editingId === section.controlId ? (
                                <div className="space-y-2">
                                    <label className="text-sm font-medium">Narrative Override</label>
                                    <Textarea
                                        value={editValue}
                                        onChange={e => setEditValue(e.target.value)}
                                        rows={5}
                                    />
                                    <div className="flex gap-2">
                                        <Button onClick={() => handleSave(section.controlId)}>Save Override</Button>
                                        <Button variant="outline" onClick={() => setEditingId(null)}>Cancel</Button>
                                    </div>
                                </div>
                            ) : (
                                <div className="space-y-2">
                                    <div className="bg-muted p-3 rounded text-sm whitespace-pre-wrap">
                                        {section.source.humanOverride ? section.source.humanOverride.narrative : section.source.autoGenerated.narrative}
                                    </div>
                                    {section.source.humanOverride && (
                                        <div className="text-xs text-muted-foreground">
                                            Overridden by {section.source.humanOverride.editedBy} on {new Date(section.source.humanOverride.editedAt).toLocaleDateString()}
                                        </div>
                                    )}
                                    <Button variant="secondary" size="sm" onClick={() => handleEdit(section)}>
                                        {section.source.humanOverride ? 'Edit Override' : 'Override Auto-Gen'}
                                    </Button>
                                </div>
                            )}

                            {/* Diff View if Stale/Conflict needed - Placeholder */}
                            {section.stale && editingId === section.controlId && (
                                <div className="mt-4 p-4 border rounded bg-orange-50 dark:bg-orange-950/20">
                                    <h4 className="font-semibold text-orange-700 text-sm mb-2">Auto-Generated Update Available (Conflict)</h4>
                                    <div className="text-xs font-mono text-muted-foreground">
                                        {section.source.autoGenerated.narrative}
                                    </div>
                                </div>
                            )}
                        </CardContent>
                    </Card>
                ))}
            </div>
        </div>
    );
}
