/**
 * Determines how compliance gaps affect execution.
 */
export type ComplianceEnforcementLevel = 'ADVISORY' | 'WARNING' | 'BLOCKING';

/**
 * Rich compliance metadata for a Capability.
 * Replaces the flat `oscalControlIds?: string[]` field.
 */
export interface CapabilityCompliance {
    /**
     * NIST/OSCAL Control IDs this capability helps satisfy.
     * Maps to OSCAL Component Definition "implemented-requirements".
     * @example ["AC-2", "AC-6(1)", "AU-3"]
     */
    satisfiesControls: string[];

    /**
     * Controls that MUST be satisfied before this capability can execute.
     * Checked at runtime by the Compliance Advisor.
     * @example ["IA-2"] // Requires authentication control
     */
    requiresControls?: string[];

    /**
     * Pointer to the SSP section with implementation narrative.
     * Enables bidirectional linking between code and documentation.
     * @example "ssp://ac-2/implementation/capability-rbac-enforcer"
     */
    implementationRef?: string;

    /**
     * Evidence artifacts this capability produces.
     * Linked in OSCAL Assessment Results.
     * @example ["audit-log://access-control-events"]
     */
    producesEvidence?: string[];

    /**
     * Version of the control mapping. Incremented when mappings change.
     * Used to detect stale SSP data (see §5.3 Staleness Detection).
     */
    mappingVersion: number;
}

/**
 * Per-tenant compliance configuration.
 * Stored in tenant settings, drives runtime behavior.
 */
export interface TenantComplianceConfig {
    /** Master switch for compliance features */
    enabled: boolean;

    /** OSCAL Profile ID to use for this tenant */
    profileId: string; // e.g., "nist-800-53-moderate", "fedramp-moderate"

    /** Default enforcement level for all controls */
    defaultEnforcement: ComplianceEnforcementLevel;

    /**
     * Per-family overrides for enforcement level.
     * Takes precedence over defaultEnforcement.
     */
    familyOverrides: {
        family: string;  // e.g., "AC", "AU", "SC"
        enforcement: ComplianceEnforcementLevel;
    }[];

    /**
     * Per-control overrides (most specific).
     */
    controlOverrides: {
        controlId: string;
        enforcement: ComplianceEnforcementLevel;
    }[];

    /** SSP generation settings */
    ssp: {
        autoGenerate: boolean;
        /** Control families where human edits require approval */
        approvalRequiredFamilies: string[];
        /** Polling interval for staleness check (minutes) */
        stalenessCheckIntervalMinutes: number;
    };
}

/**
 * Represents a single control implementation section in the SSP.
 * Tracks auto-generated vs human-edited content.
 */
export interface SSPControlSection {
    controlId: string;

    /** Content source tracking */
    source: {
        /** Auto-generated from capability metadata */
        autoGenerated: {
            narrative: string;
            generatedAt: string; // ISO timestamp
            sourceCapabilities: string[]; // Capability IDs that contributed
            mappingVersions: Record<string, number>; // capabilityId -> mappingVersion
        };

        /** Human-authored override (if any) */
        humanOverride?: {
            narrative: string;
            editedBy: string;
            editedAt: string;

            /** Approval status for security-critical families */
            approval?: {
                required: boolean;
                status: 'PENDING' | 'APPROVED' | 'REJECTED';
                approvedBy?: string;
                approvedAt?: string;
                comments?: string;
            };
        };
    };

    /** Staleness indicator (see §5.3) */
    stale: boolean;
    staleReason?: string;

    /** Evidence links */
    evidenceLinks: string[];

    /** Responsibility assignment */
    responsibleRoles: string[];
}

/**
 * Result of a pre-execution compliance check.
 */
export interface ComplianceCheckResult {
    /** Can the operation proceed? */
    canProceed: boolean;

    /** Effective enforcement level for this operation */
    enforcementLevel: ComplianceEnforcementLevel;

    /** Controls that are satisfied by the involved capabilities */
    satisfiedControls: {
        controlId: string;
        satisfiedBy: string[]; // Capability IDs
    }[];

    /** Controls required but not satisfied */
    unsatisfiedControls: {
        controlId: string;
        requiredBy: string; // Capability that declared the requirement
        enforcementLevel: ComplianceEnforcementLevel;
        recommendations: string[]; // Suggested capabilities to add
    }[];

    /** If blocked, why? */
    blockReason?: string;

    /** Actions user can take */
    remediationOptions: {
        type: 'ADD_CAPABILITY' | 'REQUEST_APPROVAL' | 'ACKNOWLEDGE_WARNING';
        description: string;
        actionPayload: unknown;
    }[];

    /** Attestation requirement */
    attestationRequired: boolean;
    attestationMessage?: string;
}

/**
 * Compliance context added to Agent Decision Records.
 */
export interface AgentDecisionComplianceContext {
    /** Profile in effect at decision time */
    activeProfileId: string;

    /** Enforcement level in effect */
    enforcementLevel: ComplianceEnforcementLevel;

    /** Controls this decision addresses */
    addressesControls: string[];

    /** Controls required but not yet satisfied */
    outstandingControls: string[];

    /** Was execution blocked? */
    blocked: boolean;

    /** Block reason if blocked */
    blockReason?: string;

    /** Acknowledgments made (for WARNING level) */
    acknowledgments: {
        controlId: string;
        acknowledgedBy: string;
        acknowledgedAt: string;
    }[];
}
