import {
    SSPControlSection,
    CapabilityCompliance,
    ComplianceEnforcementLevel
} from '@golden/schema-registry';
import { InvolvedCapability } from '@golden/compliance';

export class SSPGenerator {
    /**
     * Generates SSP control sections based on a set of capabilities.
     * This logic aggregates "satisfiesControls" claims from capabilities
     * into a draft SSP narrative.
     */
    static generateSSP(capabilities: InvolvedCapability[]): SSPControlSection[] {
        const sections = new Map<string, SSPControlSection>();

        for (const cap of capabilities) {
            if (!cap.compliance) continue;

            for (const controlId of cap.compliance.satisfiesControls) {
                if (!sections.has(controlId)) {
                    sections.set(controlId, this.createEmptySection(controlId));
                }

                const section = sections.get(controlId)!;
                this.appendCapabilityToSection(section, cap.id, cap.compliance);
            }
        }

        return Array.from(sections.values());
    }

    private static createEmptySection(controlId: string): SSPControlSection {
        return {
            controlId,
            source: {
                autoGenerated: {
                    narrative: '',
                    generatedAt: new Date().toISOString(),
                    sourceCapabilities: [],
                    mappingVersions: {}
                }
            },
            stale: false,
            evidenceLinks: [],
            responsibleRoles: []
        };
    }

    private static appendCapabilityToSection(
        section: SSPControlSection,
        capId: string,
        compliance: CapabilityCompliance
    ) {
        const autoGen = section.source.autoGenerated;

        // Add capability ID
        if (!autoGen.sourceCapabilities.includes(capId)) {
            autoGen.sourceCapabilities.push(capId);
        }

        // Track mapping version
        autoGen.mappingVersions[capId] = compliance.mappingVersion;

        // Append narrative (simple concatenation for now, could be templated)
        const newNarrative = `Satisfied by capability: ${capId} (v${compliance.mappingVersion})\n`;
        if (compliance.implementationRef) {
            autoGen.narrative += `${newNarrative}Ref: ${compliance.implementationRef}\n\n`;
        } else {
            autoGen.narrative += `${newNarrative}\n`;
        }

        // Aggregate evidence links
        if (compliance.producesEvidence) {
            for (const link of compliance.producesEvidence) {
                if (!section.evidenceLinks.includes(link)) {
                    section.evidenceLinks.push(link);
                }
            }
        }
    }
}
