import { describe, it, expect } from 'vitest';
import { SSPGenerator } from './generator.js';
import { InvolvedCapability } from '@golden/compliance';
import { CapabilityCompliance } from '@golden/schema-registry';

describe('SSPGenerator', () => {
    const capA: InvolvedCapability = {
        id: 'cap-auth',
        compliance: {
            satisfiesControls: ['IA-2', 'AC-2'],
            mappingVersion: 1,
            implementationRef: 'ssp://auth/impl'
        } as CapabilityCompliance
    };

    const capB: InvolvedCapability = {
        id: 'cap-logging',
        compliance: {
            satisfiesControls: ['AU-3'],
            mappingVersion: 2,
            producesEvidence: ['log://audit']
        } as CapabilityCompliance
    };

    it('should generate sections for all satisfied controls', () => {
        const ssp = SSPGenerator.generateSSP([capA, capB]);

        expect(ssp).toHaveLength(3); // IA-2, AC-2, AU-3
        const ids = ssp.map(s => s.controlId).sort();
        expect(ids).toEqual(['AC-2', 'AU-3', 'IA-2']);
    });

    it('should consolidate multiple capabilities for same control', () => {
        const capC: InvolvedCapability = {
            id: 'cap-extra',
            compliance: {
                satisfiesControls: ['IA-2'],
                mappingVersion: 1
            } as CapabilityCompliance
        };

        const ssp = SSPGenerator.generateSSP([capA, capC]);
        const ia2 = ssp.find(s => s.controlId === 'IA-2');

        expect(ia2).toBeDefined();
        expect(ia2!.source.autoGenerated.sourceCapabilities).toHaveLength(2);
        expect(ia2!.source.autoGenerated.sourceCapabilities).toContain('cap-auth');
        expect(ia2!.source.autoGenerated.sourceCapabilities).toContain('cap-extra');
    });
});
