/**
 * packages/capabilities/src/registry.ts
 * In-process registry for OCS capabilities by ID.
 *
 * Generated by @golden/path:sync (deterministic).
 */
import type { Capability } from '@golden/core';
import { jwtUtilitiesCapability } from './auth/jwt-utilities.capability.js';
import { oauthProviderCapability } from './auth/oauth-provider.capability.js';
import { echoCapability } from './demo/echo.capability.js';
import { githubGraphqlQueryCapability } from './connectors/github-graphql-query.capability.js';
import { githubRestRequestCapability } from './connectors/github-rest-request.capability.js';
import { jiraIssueCountCapability } from './connectors/jira-issue-count.capability.js';
import { jiraIssueSearchCapability } from './connectors/jira-issue-search.capability.js';
import { mathAddCapability } from './demo/math-add.capability.js';
import { clamavScannerCapability } from './security/clamav-scanner.capability.js';
import { semgrepScannerCapability } from './security/semgrep-scanner.capability.js';
import { trivyScannerCapability } from './security/trivy-scanner.capability.js';
import { compressionCapability } from './utilities/compression.capability.js';
import { hashingCapability } from './utilities/hashing.capability.js';
import { jsonYamlTransformCapability } from './utilities/json-yaml-transform.capability.js';

export type CapabilityRegistry = Map<string, Capability<unknown, unknown, unknown, unknown>>;

export function createCapabilityRegistry(): CapabilityRegistry {
  return new Map([
    [jwtUtilitiesCapability.metadata.id, jwtUtilitiesCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [oauthProviderCapability.metadata.id, oauthProviderCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [echoCapability.metadata.id, echoCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [githubGraphqlQueryCapability.metadata.id, githubGraphqlQueryCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [githubRestRequestCapability.metadata.id, githubRestRequestCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [jiraIssueCountCapability.metadata.id, jiraIssueCountCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [jiraIssueSearchCapability.metadata.id, jiraIssueSearchCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [mathAddCapability.metadata.id, mathAddCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [clamavScannerCapability.metadata.id, clamavScannerCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [semgrepScannerCapability.metadata.id, semgrepScannerCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [trivyScannerCapability.metadata.id, trivyScannerCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [compressionCapability.metadata.id, compressionCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [hashingCapability.metadata.id, hashingCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
    [jsonYamlTransformCapability.metadata.id, jsonYamlTransformCapability as unknown as Capability<unknown, unknown, unknown, unknown>],
  ]);
}

export function getCapability(
  registry: CapabilityRegistry,
  capId: string
): Capability<unknown, unknown, unknown, unknown> {
  const cap = registry.get(capId);
  if (!cap) throw new Error(`Capability not found: ${capId}`);
  return cap;
}
